config_refresh.overview:
  path: 'admin/config/development/configuration/refresh/overview'
  defaults:
    _controller: '\Drupal\config_refresh\Controller\ConfigRefreshController::overview'
  requirements:
    _permission: 'refresh configuration'

config_refresh.form:
  path: 'admin/config/development/configuration/refresh/form'
  defaults:
    _form: '\Drupal\config_refresh\Form\ConfigRefreshForm'
  requirements:
    _permission: 'refresh configuration'
