name: 'Config Refresh'
description: 'Provides an option to refresh configuration shipped with a module to updated with current changes'
core: 8.x
type: module
version: VERSION
package: Development
#configure: admin/reports/config-inspector
#dependencies:
#  - config
